/*
 * PLEASE NOTE: 
 * 
 * This file is automatically generated by tag_dll.awk.
 * It contains tag_typedef_t for tag references.
 * 
 * Do not, repeat, do not edit this file. Edit 'nua_tag.c' instead.
 * 
 */

#include "config.h"

#include <sofia-sip/su_tag_class.h>

#ifdef _WIN32
#define EXPORT __declspec(dllexport)
#else
#define EXPORT
#endif

#include <stddef.h>

#undef TAG_NAMESPACE
#define TAG_NAMESPACE "nua"

extern tag_typedef_t nutag_url;
EXPORT tag_typedef_t nutag_url_ref = 
  REFTAG_TYPEDEF(nutag_url);
extern tag_typedef_t nutag_address;
EXPORT tag_typedef_t nutag_address_ref = 
  REFTAG_TYPEDEF(nutag_address);
extern tag_typedef_t nutag_uicc;
EXPORT tag_typedef_t nutag_uicc_ref = 
  REFTAG_TYPEDEF(nutag_uicc);
extern tag_typedef_t nutag_media_features;
EXPORT tag_typedef_t nutag_media_features_ref = 
  REFTAG_TYPEDEF(nutag_media_features);
extern tag_typedef_t nutag_callee_caps;
EXPORT tag_typedef_t nutag_callee_caps_ref = 
  REFTAG_TYPEDEF(nutag_callee_caps);
extern tag_typedef_t nutag_early_media;
EXPORT tag_typedef_t nutag_early_media_ref = 
  REFTAG_TYPEDEF(nutag_early_media);
extern tag_typedef_t nutag_media_enable;
EXPORT tag_typedef_t nutag_media_enable_ref = 
  REFTAG_TYPEDEF(nutag_media_enable);
extern tag_typedef_t nutag_soa_session;
EXPORT tag_typedef_t nutag_soa_session_ref = 
  REFTAG_TYPEDEF(nutag_soa_session);
extern tag_typedef_t nutag_soa_name;
EXPORT tag_typedef_t nutag_soa_name_ref = 
  REFTAG_TYPEDEF(nutag_soa_name);
extern tag_typedef_t nutag_media_subsystem;
EXPORT tag_typedef_t nutag_media_subsystem_ref = 
  REFTAG_TYPEDEF(nutag_media_subsystem);
extern tag_typedef_t nutag_media_session;
EXPORT tag_typedef_t nutag_media_session_ref = 
  REFTAG_TYPEDEF(nutag_media_session);
extern tag_typedef_t nutag_retry_count;
EXPORT tag_typedef_t nutag_retry_count_ref = 
  REFTAG_TYPEDEF(nutag_retry_count);
extern tag_typedef_t nutag_max_subscriptions;
EXPORT tag_typedef_t nutag_max_subscriptions_ref = 
  REFTAG_TYPEDEF(nutag_max_subscriptions);
extern tag_typedef_t nutag_callstate;
EXPORT tag_typedef_t nutag_callstate_ref = 
  REFTAG_TYPEDEF(nutag_callstate);
extern tag_typedef_t nutag_offer_recv;
EXPORT tag_typedef_t nutag_offer_recv_ref = 
  REFTAG_TYPEDEF(nutag_offer_recv);
extern tag_typedef_t nutag_answer_recv;
EXPORT tag_typedef_t nutag_answer_recv_ref = 
  REFTAG_TYPEDEF(nutag_answer_recv);
extern tag_typedef_t nutag_offer_sent;
EXPORT tag_typedef_t nutag_offer_sent_ref = 
  REFTAG_TYPEDEF(nutag_offer_sent);
extern tag_typedef_t nutag_answer_sent;
EXPORT tag_typedef_t nutag_answer_sent_ref = 
  REFTAG_TYPEDEF(nutag_answer_sent);
extern tag_typedef_t nutag_substate;
EXPORT tag_typedef_t nutag_substate_ref = 
  REFTAG_TYPEDEF(nutag_substate);
extern tag_typedef_t nutag_invite_timer;
EXPORT tag_typedef_t nutag_invite_timer_ref = 
  REFTAG_TYPEDEF(nutag_invite_timer);
extern tag_typedef_t nutag_session_timer;
EXPORT tag_typedef_t nutag_session_timer_ref = 
  REFTAG_TYPEDEF(nutag_session_timer);
extern tag_typedef_t nutag_min_se;
EXPORT tag_typedef_t nutag_min_se_ref = 
  REFTAG_TYPEDEF(nutag_min_se);
extern tag_typedef_t nutag_session_refresher;
EXPORT tag_typedef_t nutag_session_refresher_ref = 
  REFTAG_TYPEDEF(nutag_session_refresher);
extern tag_typedef_t nutag_update_refresh;
EXPORT tag_typedef_t nutag_update_refresh_ref = 
  REFTAG_TYPEDEF(nutag_update_refresh);
extern tag_typedef_t nutag_refer_expires;
EXPORT tag_typedef_t nutag_refer_expires_ref = 
  REFTAG_TYPEDEF(nutag_refer_expires);
extern tag_typedef_t nutag_autoAlert;
EXPORT tag_typedef_t nutag_autoAlert_ref = 
  REFTAG_TYPEDEF(nutag_autoAlert);
extern tag_typedef_t nutag_autoAnswer;
EXPORT tag_typedef_t nutag_autoAnswer_ref = 
  REFTAG_TYPEDEF(nutag_autoAnswer);
extern tag_typedef_t nutag_autoACK;
EXPORT tag_typedef_t nutag_autoACK_ref = 
  REFTAG_TYPEDEF(nutag_autoACK);
extern tag_typedef_t nutag_enableInvite;
EXPORT tag_typedef_t nutag_enableInvite_ref = 
  REFTAG_TYPEDEF(nutag_enableInvite);
extern tag_typedef_t nutag_enableMessage;
EXPORT tag_typedef_t nutag_enableMessage_ref = 
  REFTAG_TYPEDEF(nutag_enableMessage);
extern tag_typedef_t nutag_enableMessenger;
EXPORT tag_typedef_t nutag_enableMessenger_ref = 
  REFTAG_TYPEDEF(nutag_enableMessenger);
extern tag_typedef_t nutag_smime_enable;
EXPORT tag_typedef_t nutag_smime_enable_ref = 
  REFTAG_TYPEDEF(nutag_smime_enable);
extern tag_typedef_t nutag_smime_opt;
EXPORT tag_typedef_t nutag_smime_opt_ref = 
  REFTAG_TYPEDEF(nutag_smime_opt);
extern tag_typedef_t nutag_smime_protection_mode;
EXPORT tag_typedef_t nutag_smime_protection_mode_ref = 
  REFTAG_TYPEDEF(nutag_smime_protection_mode);
extern tag_typedef_t nutag_smime_message_digest;
EXPORT tag_typedef_t nutag_smime_message_digest_ref = 
  REFTAG_TYPEDEF(nutag_smime_message_digest);
extern tag_typedef_t nutag_smime_signature;
EXPORT tag_typedef_t nutag_smime_signature_ref = 
  REFTAG_TYPEDEF(nutag_smime_signature);
extern tag_typedef_t nutag_smime_key_encryption;
EXPORT tag_typedef_t nutag_smime_key_encryption_ref = 
  REFTAG_TYPEDEF(nutag_smime_key_encryption);
extern tag_typedef_t nutag_smime_message_encryption;
EXPORT tag_typedef_t nutag_smime_message_encryption_ref = 
  REFTAG_TYPEDEF(nutag_smime_message_encryption);
extern tag_typedef_t nutag_sips_url;
EXPORT tag_typedef_t nutag_sips_url_ref = 
  REFTAG_TYPEDEF(nutag_sips_url);
extern tag_typedef_t nutag_certificate_dir;
EXPORT tag_typedef_t nutag_certificate_dir_ref = 
  REFTAG_TYPEDEF(nutag_certificate_dir);
extern tag_typedef_t nutag_certificate_phrase;
EXPORT tag_typedef_t nutag_certificate_phrase_ref = 
  REFTAG_TYPEDEF(nutag_certificate_phrase);
extern tag_typedef_t nutag_registrar;
EXPORT tag_typedef_t nutag_registrar_ref = 
  REFTAG_TYPEDEF(nutag_registrar);
extern tag_typedef_t nutag_sip_parser;
EXPORT tag_typedef_t nutag_sip_parser_ref = 
  REFTAG_TYPEDEF(nutag_sip_parser);
extern tag_typedef_t nutag_use_dialog;
EXPORT tag_typedef_t nutag_use_dialog_ref = 
  REFTAG_TYPEDEF(nutag_use_dialog);
extern tag_typedef_t nutag_auth;
EXPORT tag_typedef_t nutag_auth_ref = 
  REFTAG_TYPEDEF(nutag_auth);
extern tag_typedef_t nutag_authtime;
EXPORT tag_typedef_t nutag_authtime_ref = 
  REFTAG_TYPEDEF(nutag_authtime);
extern tag_typedef_t nutag_event;
EXPORT tag_typedef_t nutag_event_ref = 
  REFTAG_TYPEDEF(nutag_event);
extern tag_typedef_t nutag_status;
EXPORT tag_typedef_t nutag_status_ref = 
  REFTAG_TYPEDEF(nutag_status);
extern tag_typedef_t nutag_phrase;
EXPORT tag_typedef_t nutag_phrase_ref = 
  REFTAG_TYPEDEF(nutag_phrase);
extern tag_typedef_t nutag_handle;
EXPORT tag_typedef_t nutag_handle_ref = 
  REFTAG_TYPEDEF(nutag_handle);
extern tag_typedef_t nutag_hold;
EXPORT tag_typedef_t nutag_hold_ref = 
  REFTAG_TYPEDEF(nutag_hold);
extern tag_typedef_t nutag_notify_refer;
EXPORT tag_typedef_t nutag_notify_refer_ref = 
  REFTAG_TYPEDEF(nutag_notify_refer);
extern tag_typedef_t nutag_refer_event;
EXPORT tag_typedef_t nutag_refer_event_ref = 
  REFTAG_TYPEDEF(nutag_refer_event);
extern tag_typedef_t nutag_refer_pause;
EXPORT tag_typedef_t nutag_refer_pause_ref = 
  REFTAG_TYPEDEF(nutag_refer_pause);
extern tag_typedef_t nutag_user_agent;
EXPORT tag_typedef_t nutag_user_agent_ref = 
  REFTAG_TYPEDEF(nutag_user_agent);
extern tag_typedef_t nutag_allow;
EXPORT tag_typedef_t nutag_allow_ref = 
  REFTAG_TYPEDEF(nutag_allow);
extern tag_typedef_t nutag_path_enable;
EXPORT tag_typedef_t nutag_path_enable_ref = 
  REFTAG_TYPEDEF(nutag_path_enable);
extern tag_typedef_t nutag_service_route_enable;
EXPORT tag_typedef_t nutag_service_route_enable_ref = 
  REFTAG_TYPEDEF(nutag_service_route_enable);
extern tag_typedef_t _nutag_add_contact;
EXPORT tag_typedef_t _nutag_add_contact_ref = 
  REFTAG_TYPEDEF(_nutag_add_contact);
extern tag_typedef_t _nutag_copy;
EXPORT tag_typedef_t _nutag_copy_ref = 
  REFTAG_TYPEDEF(_nutag_copy);

EXPORT tag_type_t nua_tag_list[] =
{
  nutag_retry_count,
  nutag_uicc,
  nutag_smime_opt,
  nutag_sips_url,
  nutag_enableInvite,
  nutag_soa_session,
  nutag_path_enable,
  nutag_certificate_dir,
  nutag_authtime,
  nutag_answer_sent,
  nutag_smime_signature,
  nutag_smime_message_encryption,
  _nutag_copy,
  nutag_auth,
  nutag_min_se,
  nutag_url,
  nutag_notify_refer,
  nutag_early_media,
  nutag_service_route_enable,
  nutag_smime_message_digest,
  nutag_use_dialog,
  nutag_invite_timer,
  nutag_session_timer,
  nutag_phrase,
  nutag_offer_recv,
  nutag_media_subsystem,
  _nutag_add_contact,
  nutag_max_subscriptions,
  nutag_smime_enable,
  nutag_answer_recv,
  nutag_session_refresher,
  nutag_user_agent,
  nutag_soa_name,
  nutag_update_refresh,
  nutag_substate,
  nutag_address,
  nutag_autoAnswer,
  nutag_media_features,
  nutag_certificate_phrase,
  nutag_refer_event,
  nutag_refer_expires,
  nutag_registrar,
  nutag_status,
  nutag_refer_pause,
  nutag_autoACK,
  nutag_allow,
  nutag_handle,
  nutag_sip_parser,
  nutag_callee_caps,
  nutag_hold,
  nutag_smime_key_encryption,
  nutag_enableMessenger,
  nutag_smime_protection_mode,
  nutag_event,
  nutag_media_enable,
  nutag_callstate,
  nutag_enableMessage,
  nutag_offer_sent,
  nutag_autoAlert,
  nutag_media_session,
  NULL
};
