#! /bin/bash

rc=0

if $VALGRIND ./su_test ; then
    echo PASS: multithread su_test
else
    echo FAIL: multithread su_test failed
    rc=1
fi

if $VALGRIND ./su_test -s ; then
    echo PASS: singlethread su_test
else
    echo FAIL: singlethread su_test failed
    rc=1
fi

exit $rc
