/**@SIP
 * 
 * @cfile sip_p_tag.c  SIP Tags.
 *
 * This file is automatically generated from <sip_p_headers.h.in> by msg_parser.awk.
 *
 * @par Contributor(s):
 * - Pekka Pessi <Pekka.Pessi@nokia.com>.
 *
 * @date Created: Wed Mar 30 21:00:09 EEST 2005 ppessi
 */

#include "config.h"

#include <assert.h>
#include <stddef.h>
#include <string.h>

#include <su.h>

#define TAG_NAMESPACE "sip"

#include "sip_parser.h"
#include <sip_p_headers.h>

#include <su_tag_class.h>
#include <su_tag_inline.h>
#include <sip_tag_class.h>

SIP_DLL extern tag_class_t siphdrtag_class[1];
SIP_DLL extern tag_class_t sipstrtag_class[1];


/**@ingroup sip_p_asserted_identity
 * Tag for P-Asserted-Identity header object.
 */
tag_typedef_t siptag_p_asserted_identity = SIPHDRTAG_TYPEDEF(p_asserted_identity);
/**@ingroup sip_p_asserted_identity
 * Tag for string with P-Asserted-Identity header value.
 */
tag_typedef_t siptag_p_asserted_identity_str = SIPSTRTAG_TYPEDEF(p_asserted_identity);

/**@ingroup sip_p_preferred_identity
 * Tag for P-Preferred-Identity header object.
 */
tag_typedef_t siptag_p_preferred_identity = SIPHDRTAG_TYPEDEF(p_preferred_identity);
/**@ingroup sip_p_preferred_identity
 * Tag for string with P-Preferred-Identity header value.
 */
tag_typedef_t siptag_p_preferred_identity_str = SIPSTRTAG_TYPEDEF(p_preferred_identity);

/**@ingroup sip_p_associated_uri
 * Tag for P-Associated-URI header object.
 */
tag_typedef_t siptag_p_associated_uri = SIPHDRTAG_TYPEDEF(p_associated_uri);
/**@ingroup sip_p_associated_uri
 * Tag for string with P-Associated-URI header value.
 */
tag_typedef_t siptag_p_associated_uri_str = SIPSTRTAG_TYPEDEF(p_associated_uri);

/**@ingroup sip_p_called_party_id
 * Tag for P-Called-Party-ID header object.
 */
tag_typedef_t siptag_p_called_party_id = SIPHDRTAG_TYPEDEF(p_called_party_id);
/**@ingroup sip_p_called_party_id
 * Tag for string with P-Called-Party-ID header value.
 */
tag_typedef_t siptag_p_called_party_id_str = SIPSTRTAG_TYPEDEF(p_called_party_id);

/**@ingroup sip_p_visited_network_id
 * Tag for P-Visited-Network-ID header object.
 */
tag_typedef_t siptag_p_visited_network_id = SIPHDRTAG_TYPEDEF(p_visited_network_id);
/**@ingroup sip_p_visited_network_id
 * Tag for string with P-Visited-Network-ID header value.
 */
tag_typedef_t siptag_p_visited_network_id_str = SIPSTRTAG_TYPEDEF(p_visited_network_id);

/**@ingroup sip_p_access_network_info
 * Tag for P-Access-Network-Info header object.
 */
tag_typedef_t siptag_p_access_network_info = SIPHDRTAG_TYPEDEF(p_access_network_info);
/**@ingroup sip_p_access_network_info
 * Tag for string with P-Access-Network-Info header value.
 */
tag_typedef_t siptag_p_access_network_info_str = SIPSTRTAG_TYPEDEF(p_access_network_info);

/**@ingroup sip_p_charging_addr
 * Tag for P-Charging-Function-Addresses header object.
 */
tag_typedef_t siptag_p_charging_addr = SIPHDRTAG_TYPEDEF(p_charging_addr);
/**@ingroup sip_p_charging_addr
 * Tag for string with P-Charging-Function-Addresses header value.
 */
tag_typedef_t siptag_p_charging_addr_str = SIPSTRTAG_TYPEDEF(p_charging_addr);

/**@ingroup sip_p_charging_vector
 * Tag for P-Charging-Vector header object.
 */
tag_typedef_t siptag_p_charging_vector = SIPHDRTAG_TYPEDEF(p_charging_vector);
/**@ingroup sip_p_charging_vector
 * Tag for string with P-Charging-Vector header value.
 */
tag_typedef_t siptag_p_charging_vector_str = SIPSTRTAG_TYPEDEF(p_charging_vector);

