#! /bin/sh
# 
# Startup script for nua_cli
#
# This uses proxy on local host (port 5060) by default
#
# --------------------------------------------------------------------
#
# This file is part of the Sofia-SIP package
#
# Copyright (C) 2005 Nokia Corporation.
#
# Contact: Pekka Pessi <pekka.pessi@nokia.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA
#
# --------------------------------------------------------------------
#

# If you dont't want to have proxy, start NUA with command
# env sip_proxy="-" ./NUA

# If you want to use default port,  start NUA with command
# env sip_proxy="-" p=- ./NUA

# Export non-null variables 
function xport # [env_var...]
{
    local v
    for v
    do
	if eval test -z '"$'$v'"' || eval test X- = '"X$'$v'"'
	then
	    eval export -n $v
	else
	    eval export $v
	fi
    done
}

# Search for a command from path list
# Assign $command as full path
function search # command [path list]
{
    local p x
    x=$1; shift;
    for p
    do
	test -n "$p" && p="$p/"
	if type -t "$p$x" >/dev/null; then
	    eval $x="$p$x"
	    break;
	fi
    done
}

# Search for more exotic binaries
search ifconfig /sbin /usr/sbin
search nua_cli . ${0%/NUA*} "" /opt/iptel/bin

true ${user:=`whoami`}
true ${name:=`finger $user | awk '/^Login:.*Name: / { sub(/.*Name: /, ""); print $0; }'`}
true ${dn:=`hostname`}
test ${p:=:*} = '-' && p=
true ${ip:=`$ifconfig eth0 | awk '/inet addr:/ { sub(/addr:/, "", $2); print $2; }'`}

#
# Set signaling parameters
#

# Dump all signaling messages to specified file 
true ${MSG_DUMP:=}

# If non-empty, nua_cli prints all signaling messages
true ${MSG_STREAM_LOG:=}

# This address is used in From (and To of REGISTER)
true ${SIPADDRESS:="$name<sip:$user@$dn>"}

# This is our Call-info (defaults to icon found on local host)
true ${SIPCALLINFO:="<http://$dn:$p/image.img>;purpose=icon"}

# This is our contact
true ${contact:="sip:$user@$ip$p;maddr=*"}

# This is our proxy
# This defaults to a proxy at 5060 port in local host
# Note: This requires that a separate proxy process is run 
# and we register to it.

true ${sip_proxy:="sip:$ip"}

# Our product name
true ${USERAGENT:=NUA 0.2/NTA 1.1}

xport MSG_DUMP MSG_STREAM_LOG SIPADDRESS SIPCALLINFO sip_proxy 

#
# Media parameters
#
# Address used by SDP
true ${HOSTADDRESS:=$ip}
# Media codecs in use
true ${SMM_AUDIO_CODECS=PCMA,PCMU,L16}

xport HOSTADDRESS SMM_AUDIO_CODECS
exec $nua_cli $contact
