#! /bin/sh
#
# Add lcov results from last check run to ${top_srcdir}/lcov/module

#
# Copyright (C) 2007 Nokia Corporation
# Contact: Pekka Pessi <pekka.pessi@nokia.com>
# Licensed under LGPL. See file COPYING.
#

usage()
{
  test X$1 == X0 || exec >&2
  echo usage: add-coverage [--top_builddir=DIR] [--top_srcdir=DIR] [PATH]
  exit $1;
}

bdir=`pwd`;
prefix=lcov/

top=.
case $0 in */*) top=${0%/scripts/*} top_srcdir=$top;; esac

while test $# -gt 0;
do
  case $1 in 
  --top_builddir ) test -z "$2" && usage 1; shift; top=$1; shift; ;;
  --top_builddir=* ) top=${1#--top_builddir=}; shift ;;
  --top_srcdir ) test -z "$2" && usage 1; shift; top=$1; shift; ;;
  --top_srcdir=* ) top=${1#--top_srcdir=}; shift ;;
  - ) shift; break ;;
  -* ) usage 1; ;;
  * ) break ;;
  esac
done

abs_srcdir=`cd $top_srcdir; pwd`
cd $top
tdir=`pwd`;

if test $tdir != $bdir; then
  prefix=lcov${bdir#$tdir}
fi

p=$prefix/$1

mkdir -p lcov

case $p in 
lcov/ )
  echo libsofia-sip-ua lcov/libsofia-sip-ua.info
  echo libsofia-sip-ua-glib lcov/libsofia-sip-ua-glib.info
  ;;
lcov/?* ) 
  base=${p#lcov/} 
  echo ${base%/} lcov/${base%%/*}.info
  ;;
* )
  echo $0:$LINENO: internal error >& 2
  exit 2
  ;;
esac | tee /dev/tty |
while read directory outputfile
do
  # Remove changed source files 
  if test -r ${outputfile}0 ; then
    find ${abs_srcdir}/${directory} -name '*.[hc]' -newer ${outputfile}0 |
    xargs lcov -r ${outputfile}0 > ${outputfile}1 &&
    mv ${outputfile}1 ${outputfile}0
  fi
  lcov --capture --compat-libtool \
  --directory ${directory}  --output-file ${outputfile}0 &&
  { 
  # remove test programs and system includes with inlined functions
  lcov -l ${outputfile}0 | grep -v "`cd ${top_srcdir} && pwd`"
  lcov -l ${outputfile}0 | grep "/test\|/torture\|_test[.]c$"
  } | cut -d: -f1 |
  xargs lcov -r ${outputfile}0 > ${outputfile} &&
  genhtml --title "sofia-sip-current/$directory" \
     --output-directory lcov/${directory%%/*} ${outputfile}
done
